INSERT INTO keywords (keyword, language)
VALUES ('Multilingualismus', 'de'),
       ('multilingual', 'de'),
       ('multilingualer', 'de'),
       ('multilinguale', 'de'),
       ('Mehrsprachigkeit', 'de'),
       ('mehrsprachig', 'de'),
       ('mehrsprachige', 'de'),
       ('mehrsprachiger', 'de'),
       ('Zweisprachigkeit', 'de'),
       ('zweisprachig', 'de'),
       ('zweisprachige', 'de'),
       ('zweisprachiger', 'de'),
       ('Bilingualismus', 'de'),
       ('bilingual', 'de'),
       ('bilinguale', 'de'),
       ('bilingualer', 'de'),
       ('sprachliche Vielfalt', 'de'),
       ('Sprachenvielfalt', 'de'),
       ('vielfältige Sprachen', 'de'),
       ('sprachliche Heterogenität', 'de'),
       ('Heterogenität', 'de'),
       ('heterogen', 'de'),
       ('heterogene', 'de'),
       ('heterogener', 'de'),
       ('sprachlich heterogen', 'de'),
       ('sprachliche Diversität', 'de'),
       ('Diversität', 'de'),
       ('divers', 'de'),
       ('diverse', 'de'),
       ('diverser', 'de'),
       ('Diversifizierung', 'de'),
       ('sprachliche Diversifizierung', 'de'),
       ('Vielfalt', 'de'),
       ('Vielfältigkeit', 'de'),
       ('Zweitspracherwerb', 'de'),
       ('Zweitsprachen', 'de'),
       ('Zweitsprache', 'de'),
       ('Erwerb der Zweitsprache', 'de'),
       ('Spracherwerb', 'de'),
       ('Spracherwerbsprozesse', 'de'),
       ('Deutsch als Zweitspra-che', 'de'),
       ('DaZ', 'de'),
       ('Deutsch als Fremdsprache', 'de'),
       ('DaF', 'de'),
       ('Drittsprachen', 'de'),
       ('Drittsprache', 'de'),
       ('Tertiärsprache', 'de'),
       ('Herkunftssprachen', 'de'),
       ('Herkunftssprache', 'de'),
       ('Familiensprache', 'de'),
       ('Familiensprachen', 'de'),
       ('Plurilingualismus', 'de'),
       ('plurilingual', 'de'),
       ('plurilinguale', 'de'),
       ('plurilingualer', 'de'),
       ('mehrsprachige Ressourcen', 'de'),
       ('sprachliche Ressourcen', 'de'),
       ('sprachliche Repertoires', 'de'),
       ('mehrsprachige Lernende', 'de'),
       ('mehrsprachige Schüler', 'de'),
       ('mehrsprachige Schülerinnen', 'de'),
       ('mehrsprachige Kinder', 'de'),
       ('Umgang mit Mehrsprachigkeit', 'de'),
       ('Arbeit mit Mehrsprachigkeit', 'de'),
       ('sprachliche Unterschiede', 'de'),
       ('sprachliche Voraussetzungen', 'de'),
       ('sprachliche Hintergründe', 'de'),
       ('multilingualism', 'en'),
       ('multilinguality', 'en'),
       ('multilingual', 'en'),
       ('multilingual learners', 'en'),
       ('multilingual students', 'en'),
       ('bilingualism', 'en'),
       ('bilingual', 'en'),
       ('bilingual education', 'en'),
       ('linguistic diversity', 'en'),
       ('language diversity', 'en'),
       ('diversity of languages', 'en'),
       ('linguistic heterogeneity', 'en'),
       ('language heterogeneity', 'en'),
       ('heterogeneous language backgrounds', 'en'),
       ('linguistically diverse', 'en'),
       ('second language acquisition', 'en'),
       ('second language learning', 'en'),
       ('second language development', 'en'),
       ('English as a second language', 'en'),
       ('Enlish as an additional language', 'en'),
       ('language awareness', 'en'),
       ('linguistic awareness', 'en'),
       ('metalinguistic awareness', 'en'),
       ('languages of origin', 'en'),
       ('language of origin', 'en'),
       ('heritage languages', 'en'),
       ('heritage language', 'en'),
       ('home language', 'en'),
       ('home languages', 'en'),
       ('native language', 'en'),
       ('plurilingualism', 'en'),
       ('plurilingual', 'en'),
       ('plurilingual competence', 'en'),
       ('plurilingual education', 'en'),
       ('language repertoires', 'en'),
       ('language repertoire', 'en'),
       ('linguistic resources', 'en'),
       ('language resources', 'en'),
       ('multilingual resources', 'en'),
       ('diversity', 'en'),
       ('divers', 'en')
    ON CONFLICT (keyword) DO NOTHING;
